mockのテスト
azurata09/funverse_app pull request #1
Opened 2024-12-09 08:42 UTC by seisuiritoru

モックサーバー用

2024-12-13 11:28 UTC, asann3 requested changes
見ました

2024-12-13 11:28 UTC, asann3 commented on mock/dockercompose.yml
ファイル名は`docker-compose.yml`か`compose.yml`にする

2024-12-13 11:28 UTC, asann3 commented on mock/dockercompose.yml
> +version: '3.9'
```suggestion
```

Docker Compose V2 ではバージョンの明記が非推奨

2024-12-13 11:28 UTC, asann3 commented on mock/openapi.yml
> +    description: base endpoint.
```suggestion
```
Dockerでは別のポートで起動しているので必要ないかも
残す場合は、Docker Composeのymlファイルと揃える

2024-12-13 11:28 UTC, asann3 commented on mock/openapi.yml
> +openapi: 3.0.0
```suggestion
openapi: 3.1.0
```

2024-12-23 07:13 UTC, azurata09 commented
バックエンドのモックは [azurata09/funverse_server](https://github.com/azurata09/funverse_server) にあるので、そこからcloneしてきてください

2024-12-23 07:13 UTC, closed without merging